version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: censys-challenge-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: censys-challenge
    ports:
      - "5432:5432"
